version: '2'
services:
  spring-boot-fast:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-boot-fast
    restart: always
    ports:
      - '8989:8080'
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - '/opt/mysql/data:/var/lib/mysql'
  redis:
    image: redis:latest
    container_name: redis-test
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - '/opt/redis/data:/data'
