server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

knife4j:
#  markdowns: classpath:markdown/*
  basic:
    enable: false
    username: zhangsan
    password: 123456

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.liuzg.entity
  # xml 扫描路径
  mapper-locations: classpath:/mybatis/*.xml
  global-config:
    db-config:
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false