server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

knife4j:
#  markdowns: classpath:markdown/*
  basic:
    enable: false
    username: zhangsan
    password: 123456